### ISSUE TITLE
Add nullable reference annotations.

### ISSUE THREAD

**Issue by Jason5Lee** [microsoft/playwright-sharp#1504]
The playwright library has no clear documentation about whether an argument or return type can be null. In the original TypeScript library it's not a problem since the type system of TypeScript supports nullable annotation. For example, the `page.contentText` has a `string | null` type, which indicates that it may be null. With `strictNullCheck` compiler option, you can't call its methods without proper null check.

![image](https://user-images.githubusercontent.com/25118271/121101918-592be880-c82f-11eb-9e5d-4af50bc73fcb.png)

However, in this project, the nullable annotation is absent, neither the documentation points out the fact that it can be null.

![Screen Shot 2021-06-08 at 8 00 40 AM](https://user-images.githubusercontent.com/25118271/121102134-c63f7e00-c82f-11eb-9fc1-4e8862f99e5a.png)

Actually [C# has a nullable annotation](https://docs.microsoft.com/en-us/dotnet/csharp/nullable-migration-strategies) in its new version. Please properly annotate them like the TypeScript library, or at least document them.

**Comment by pavelfeldman** [comment]
We can definitely generate nullable annotations. Do you have experience consuming them? In our setting, they only were in our way due to the testing nature of the client. It is easier to make "Dereference of a possibly null reference" while testing - it it was in fact null, test would fail. What is your client's nature?

Another question is that Options bags are 95% of our API, but sadly nullable references don't improve the nullability. There is no way to make compile error when required property is missing while using late property initialization construction (See https://docs.microsoft.com/en-us/dotnet/csharp/nullable-migration-strategies#late-initialized-properties-data-transfer-objects-and-nullability).

**Comment by pavelfeldman** [comment]
ok, let's see how this works!
